### ISSUE TITLE
Error tagged bam

### ISSUE THREAD

**Issue by AntonioDeFalco** [BGSpiegl/GCparagon#5]
Hello @BGSpiegl ,
Thanks for developing this great tool. I get the output without errors but if I try to use the -ob parameter to get the tagged bam file, I get the following error (I tried with several different samples):
`Traceback (most recent call last):
  File "miniconda3/envs/GCparagon/bin/gcparagon", line 8, in <module>
    sys.exit(main())
  File "miniconda3/envs/GCparagon/lib/python3.10/site-packages/GCparagon/correct_GC_bias.py", line 3174, in main
    tag_bam_with_correction_weights_parallel(
  File "miniconda3/envs/GCparagon/lib/python3.10/site-packages/GCparagon/correct_GC_bias.py", line 2304, in tag_bam_with_correction_weights_parallel
    tagged_scaffold_bam_files_in_order = order_bams(bam_list=tagged_scaffold_bam_files)
  File "miniconda3/envs/GCparagon/lib/python3.10/site-packages/GCparagon/correct_GC_bias.py", line 2163, in order_bams
    chrm, strt, stp = Path(bam_nm).name.split('.GCcorr')[0].split('+')[-1].split('-')  # chrom-start-stop
ValueError: too many values to unpack (expected 3)
Continuing to process next BAM file..`

What could this be due to? Thank you.

Regards

**Comment by BGSpiegl** [comment]
Hi Antonio. Thank you for submitting the issue. I am sorry that you experience problems with GCparagon.

A question form my side: what was the name of your input BAM file?

GCparagon uses multiprocessing to tag alignments from different scaffolds simultaneously.
Scaffolds are subdivided in 50,000,000 Mb genomic intervals.
To avoid scrambling up the output, each process writes a separate output file inside the temporary directory, one per genomic interval at a time.
These tagging output files include a scaffold tag like this:
`BAMNAME+chr1-0-50000000.GCcorr.bam`
where `+chr1-0-50000000` identifies the processed genomic interval.

After tagging, the parent process gathers the tagged BAM file paths and concatenates them according to the scaffold order of the BAM header and the coordinates of the genomic intervals.

I ran a test sample using a slightly updated code where the troublemaker-piece of code from your stack trace tries to obtain this information from the tagged BAM file name: (warning-pseudocode)
- extract `chrm, strt, stp` from the BAM file name by
- splitting `<BAMNAME+chr1-0-50000000.GCcorr.bam>` based on substring '.GCcorr', taking the first element
- split again at character '+', taking the last element (e.g., `chr1-0-50000000`)
- split that again at characters `-` which should yield the scaffold name and the genomic coordinates 'chr1',`0` and `50000000`

This will fail if your BAM name contains multiple instances of the substring `.GCcorr`. So make sure this is not the case.
I changed now splitting to substring `.GCcorr.bam` which should work better.

Please clone the latest version v0.6.4 and retry!

**Comment by AntonioDeFalco** [comment]
Thanks for the quick response and the attempt to solve the problem, which seems to have been solved, but now I am getting another error; at first, my bam file name was ICE22_recal.bam, I even tried renaming it to ICE22.bam but I get the following error:

| 2024-01-24 23:17:20,129 - GCparagon - ERROR - The following exception occurred when trying to process BAM file ICE22.bam:
Traceback (most recent call last):
  File "miniconda3/envs/GCparagon/bin/gcparagon", line 8, in <module>
    sys.exit(main())
  File "miniconda3/envs/GCparagon/lib/python3.10/site-packages/GCparagon/correct_GC_bias.py", line 3174, in main
    tag_bam_with_correction_weights_parallel(
  File "miniconda3/envs/GCparagon/lib/python3.10/site-packages/GCparagon/correct_GC_bias.py", line 2304, in tag_bam_with_correction_weights_parallel
    tagged_scaffold_bam_files_in_order = order_bams(bam_list=tagged_scaffold_bam_files)
  File "miniconda3/envs/GCparagon/lib/python3.10/site-packages/GCparagon/correct_GC_bias.py", line 2164, in order_bams
    bam_paths_with_locus.append(((chrm, int(strt)), str(bam_nm)))
ValueError: invalid literal for int() with base 10: 'A*01:02'
Continuing to process next BAM file..

Thanks.

**Comment by BGSpiegl** [comment]
It seems there is a timestamp in the name of one of your tagged output scaffold BAM files for at least one scaffold inside your temporary directory. Can you pls have a look how these scaffold BAM files are named inside your temporary directory? If you did not specify a temporary directory (which you should definitely do), the otemporary output is likely written to your system temp under `/tmp/<sample_identifier>/` 
I have problems reproducing your error though.

As a first means of troubleshooting, please try adding the following piece of code (with same indentation as line 2164) after line 2164 in the script correct_GC_bias.py:
`print(f"{chrm}, {strt}, {stp}")`

I ran the v0.6.4 code in `--tag-only` mode to see if there might be a problem. There was none for me.
these were my command line parameters:
```--bam /some_paht_to/INPUT.bam --correction-weights /another_path_to/INPUT_gc_weights_4simsMean.2IQRoutliersRemoved.2IgaussSmoothed.txt.gz --tag-only --output-unaligned-reads --tag-name TG --temporary-directory /mnt/scratch_drive/tmp```

I need to ask you to provide the following details so that I can understand your situation better:

- your complete command line call to GCparagon
- the OS you are working on
- the hardware you are using, specifically, the temporary directory and how many cores you are using for parallel processing (e.g., is any of your paths on a remote file system?)
- are you using any custom-made files? (e.g., are you working with a non-human sample/reference genome)
- did you clone the v0.6.4 repository anew or were you using a patchwork of extended or adapted code? If not, please clone the dev branch and try again!
- have you defined the variable `annotation_str` anywhere in the code?

I encountered a problem where repeatedly outputting to the same directory fails because the output file already exists.
I changed that behavior to delete any preexisting output files before attempting to move files from the temporary directory there.

Thank you!
