### ISSUE TITLE
Why are all my sample's *.GCcontent_RefVsReconstructed.png files the same?

### ISSUE THREAD

**Issue by chenzemin** [BGSpiegl/GCparagon#6]
![SRR11809978 sorted GCcontent_RefVsReconstructed](https://github.com/BGSpiegl/GCparagon/assets/37295211/36ee50d7-dc44-4bf5-96a0-878dc6c5e07e)
I analyzed 15 samples. The original line and the reconstructed line overlap.

This is my configuration:
![image](https://github.com/BGSpiegl/GCparagon/assets/37295211/21440b62-82fb-4eee-b721-f7253d6841b1)

**Comment by BGSpiegl** [comment]
Hi chenzemin.
It seems like you are analyzing shallow sequenced sample(s) because the estimated number of processed fragments is below 7 M although 50 M was set as target (preset 2).
Therefore, the entire list of predefined genomic intervals will be used during the GC bias computation. The combined fragment GC content distribution of these genomic intervals (linear combination with region weights between 0.1 and 10, each determined individually) will always be the same if these regions are used consistently for all of your samples.

The printed graph should give an idea if the element-wise optimization is bettter than the naive combination of predefined genomic intervals. In your case, not. Therefore, the original and reconstructed lines are identical. A deviation of ~0.25 GC% of the mean remains.
Sidenote: something looks odd about the height diffference between the reconstructed curve vs. the reference GC% curve. I have to look into that. I think this just affects the visualisation, not the computation though.

Hope that helped.

**Comment by chenzemin** [comment]
> Hi chenzemin. It seems like you are analyzing shallow sequenced sample(s) because the estimated number of processed fragments is below 7 M although 50 M was set as target (preset 2). Therefore, the entire list of predefined genomic intervals will be used during the GC bias computation. The combined fragment GC content distribution of these genomic intervals (linear combination with region weights between 0.1 and 10, each determined individually) will always be the same if these regions are used consistently for all of your samples.
> 
> The printed graph should give an idea if the element-wise optimization is bettter than the naive combination of predefined genomic intervals. In your case, not. Therefore, the original and reconstructed lines are identical. A deviation of ~0.25 GC% of the mean remains. Sidenote: something looks odd about the height diffference between the reconstructed curve vs. the reference GC% curve. I have to look into that. I think this just affects the visualisation, not the computation though.
> 
> Hope that helped.

Thank you very much for your response. I indeed only used 1X depth data for analysis and utilized the preset genomic intervals provided by you in the hg38 version. So, are my GC correction results incorrect now? Is it mainly due to the influence of sequencing depth or the preset genomic intervals?

**Comment by BGSpiegl** [comment]
Why would your results be wrong? The preselected genomic intervals only determine which regions are used to compute GC bias. These regions are valid. Their combination closely resembles the expected reference GC distribution.
Only the number of fragments on which the correction is based is limited in case of processing sWGS samples. The computed bias should still be valid even if it will be more of a rough estimate.
I don't see an issue here per se.
Do you have any other reason to suspect an error in the correction? Can you probably share an image of the output weights matrix? (outliers limited and smoothed)

**Comment by BGSpiegl** [comment]
Note: I think I understand the confusion now. The graph you are looking at does not visualize the achieved correction for each sample!
GCparagon tires to combine correction results from various genomic intervals a bit more clever than just averaging them.
GCparagon combines results from genomic intervals using a weighted average, one factor for each region. This factor is computed using the reference sequence of the respective genomic interval and a reference fragment length distribution (-> "fragment GC content distribution"). This has nothing to do with the input BAM file. It is solely defined by the reference sequence and the coordinates of the preselected genomic interval. The computed FGCD (= distribution of GC content of fragments in percent) is computed for each interval using the reference genome sequence, not the alignments form the BAM file. A reference GC content distribution has also been pre-computed using the entire reference genome (this is the red curve in the plot) and the reference fragment length distribution.
This is what is meant with the plot title "_Reconstructed from Genomic Intervals vs. Genome_".

If you want to validate the correction, you would need to compute the FGCD from your corrected fragments (not the reference genome) and compare against [a valid reference GC content distribution](https://github.com/BGSpiegl/GCparagon/blob/including_EGAS00001006963_results/validation/03_genome-wide_correction_fidelity/simulated_hg38_ref_gc/hg38.analysisSet.2bit_H01-entireBAM-fragLenDist_ref_GC_dist_500Mreads.tsv) (i.e., the red distribution red in the plot; I linked the reference FGCD file for the healthy sample H01) analogous to what was done in the publication.

If you are interested in validating the correction result, have a look at the validation script [03-1_create_corrected_fragment_gc_distributions.py](https://github.com/BGSpiegl/GCparagon/blob/including_EGAS00001006963_results/validation/03-1_create_corrected_fragment_gc_distributions.py). You will find plotting code for the result in (03-3_plot_per_fragment_GC_content_correction_fidelity.py)[https://github.com/BGSpiegl/GCparagon/blob/including_EGAS00001006963_results/validation/03-3_plot_per_fragment_GC_content_correction_fidelity.py]. beware that these scripts try to compare the GCparagon correction of the 4 samples from the publication to the Griffin correction results. You would need to remove the parts of the code dealing with Griffin if you want to just compare your sample(s) against the reference GC content distribution. And of course change the paths to hte corercted sample BAM files.

I can assure you - your results are not invalid just because no improvement for combining interval results was found over naive averaging (as stated before, this happens when the preselected genomic intervals already closely mimic the reference genome GC content distribution).
